=== hihj0312/PASS/pcpartsdtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT item (CPUs, RAMs, MOTHERBOARDs, PSUs, VGAs, SSDs, HDDs, ODDs, MOUSEs, KEYBOARDs)>

<!ELEMENT CPUs (basic, general, high, highest)>
<!ELEMENT basic (cpu*)>
<!ELEMENT cpu (name, company, price, core, thread)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT core (#PCDATA)>
<!ELEMENT thread (#PCDATA)>
<!ELEMENT general (cpu*)>
<!ELEMENT high (cpu*)>
<!ELEMENT highest (cpu*)>

<!ELEMENT RAMs (ram*)>
<!ELEMENT ram (name, company, price, memorytype, capacity, memorytiming?)>
<!ELEMENT memorytype (#PCDATA)>
<!ELEMENT capacity (#PCDATA)>
<!ELEMENT memorytiming (#PCDATA)>

<!ELEMENT MOTHERBOARDs (motherboard*)>
<!ELEMENT motherboard (name, company, price, size, socket, chipset)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT socket (#PCDATA)>
<!ELEMENT chipset (#PCDATA)>

<!ELEMENT PSUs (psu*)>
<!ELEMENT psu (name, company, price, size, capacity)>

<!ELEMENT VGAs (vga*)>
<!ELEMENT vga (name, company, price, capacity, chipset)>

<!ELEMENT SSDs (ssd*)>
<!ELEMENT ssd (name, company, price, capacity, readspeed, writespeed)>
<!ELEMENT readspeed (#PCDATA)>
<!ELEMENT writespeed (#PCDATA)>

<!ELEMENT HDDs (hdd*)>
<!ELEMENT hdd (name, company, price, capacity, buffermemory)>
<!ELEMENT buffermemory (#PCDATA)>

<!ELEMENT ODDs (internal, external)>
<!ELEMENT internal (odd*)>
<!ELEMENT external (odd*)>
<!ELEMENT odd (name, company, price, record)>
<!ELEMENT record (#PCDATA)>

<!ELEMENT MOUSEs (office, game)>
<!ELEMENT office ((mouse|keyboard)*)>
<!ELEMENT game ((mouse|keyboard)*)>
<!ELEMENT mouse (name, company, price, sensitivity, response?, feature, explain?)>
<!ELEMENT keyboard (name, company, price, feature, explain?)>
<!ELEMENT sensitivity (#PCDATA)>
<!ELEMENT response (#PCDATA)>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT explain (#PCDATA)>

<!ELEMENT KEYBOARDs (office, game)>

=== hihj0312/PASS/pcparts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item SYSTEM "pcpartsdtd.dtd" >

<item>
	<CPUs>
		<basic>
			<cpu>
				<name>펜티엄 G4560 카비레이크</name>
				<company>인텔</company>
				<price>83</price>
				<core>2</core>
				<thread>4</thread>
			</cpu>
			<cpu>
				<name>A4 7300 리치랜드</name>
				<company>AMD</company>
				<price>37</price>
				<core>2</core>
				<thread>2</thread>
			</cpu>
		</basic>
		<general>
			<cpu>
				<name>i3-7100 카비레이크</name>
				<company>인텔</company>
				<price>114</price>
				<core>2</core>
				<thread>4</thread>
			</cpu>
			<cpu>
				<name>라이젠5 1400 서밋 릿지</name>
				<company>AMD</company>
				<price>181</price>
				<core>4</core>
				<thread>8</thread>
			</cpu>
			<cpu>
				<name>R5 1500 서밋 릿지</name>
				<company>AMD</company>
				<price>204</price>
				<core>4</core>
				<thread>8</thread>
			</cpu>
		</general>
		<high>
			<cpu>
				<name>i5-7600 카비레이크</name>
				<company>인텔</company>
				<price>222</price>
				<core>4</core>
				<thread>4</thread>
			</cpu>
			<cpu>
				<name>i5-7600K 카비레이크</name>
				<company>인텔</company>
				<price>248</price>
				<core>4</core>
				<thread>4</thread>
			</cpu>
			<cpu>
				<name>라이젠5 1600 서밋 릿지</name>
				<company>AMD</company>
				<price>231</price>
				<core>6</core>
				<thread>12</thread>
			</cpu>
		</high>
		<highest>
			<cpu>
				<name>i7-7700 카비레이크</name>
				<company>인텔</company>
				<price>328</price>
				<core>4</core>
				<thread>8</thread>
			</cpu>
			<cpu>
				<name>i7-7700k 카비레이크</name>
				<company>인텔</company>
				<price>351</price>
				<core>4</core>
				<thread>8</thread>
			</cpu>
			<cpu>
				<name>라이젠7 1700 서밋 릿지</name>
				<company>AMD</company>
				<price>345</price>
				<core>8</core>
				<thread>16</thread>
			</cpu>
			<cpu>
				<name>R7 1800X 서밋 릿지</name>
				<company>AMD</company>
				<price>558</price>
				<core>8</core>
				<thread>16</thread>
			</cpu>
		</highest>
	</CPUs>
	<RAMs>
		<ram>
			<name>PC4-19200</name>
			<company>삼성전자</company>
			<price>75</price>
			<memorytype>DDR4</memorytype>
			<capacity>8</capacity>
			<memorytiming>17-18-18(비공식)</memorytiming>
		</ram>
		<ram>
			<name>KLEVV PC4-19200 CL15</name>
			<company>ESSENCORE</company>
			<price>76</price>
			<memorytype>DDR4</memorytype>
			<capacity>8</capacity>
			<memorytiming>15-15-15</memorytiming>
		</ram>
		<ram>
			<name>PC4-19200 CL17</name>
			<company>타무즈</company>
			<price>72</price>
			<memorytype>DDR4</memorytype>
			<capacity>8</capacity>
			<memorytiming>17-17-17-39</memorytiming>
		</ram>
		<ram>
			<name>PC4-19200 CL15 TRIDENT Z RGB</name>
			<company>G.SKILL</company>
			<price>207</price>
			<memorytype>DDR4</memorytype>
			<capacity>16(8x2)</capacity>
			<memorytiming>15-15-15-35</memorytiming>
		</ram>
		<ram>
			<name>PC3-12800</name>
			<company>삼성전자</company>
			<price>66</price>
			<memorytype>DDR3</memorytype>
			<capacity>8</capacity>
			<memorytiming></memorytiming>
		</ram>
		<ram>
			<name>PC3-12800</name>
			<company>삼성전자</company>
			<price>75</price>
			<memorytype>DDR4</memorytype>
			<capacity>8</capacity>
			<memorytiming></memorytiming>
		</ram>
		<ram>
			<name>T-Force PC4-25600 CL16 Night Hawk RGB</name>
			<company>TeamGroup</company>
			<price>262</price>
			<memorytype>DDR4</memorytype>
			<capacity>16(8x2)</capacity>
			<memorytiming>16-18-18-38</memorytiming>
		</ram>
		<ram>
			<name>PC4-19200 CL16 EVO-X WHITE RYZEN RGB</name>
			<company>GeIL</company>
			<price>203</price>
			<memorytype>DDR4</memorytype>
			<capacity>16(8x2)</capacity>
			<memorytiming>16-16-16-36</memorytiming>
		</ram>
		<ram>
			<name>PC4-19200</name>
			<company>삼성전자</company>
			<price>174</price>
			<memorytype>DDR4</memorytype>
			<capacity>16</capacity>
			<memorytiming></memorytiming>
		</ram>
		<ram>
			<name>PC4-17000</name>
			<company>삼성전자</company>
			<price>34</price>
			<memorytype>DDR4</memorytype>
			<capacity>4</capacity>
			<memorytiming></memorytiming>
		</ram>
	</RAMs>
	<MOTHERBOARDs>
		<motherboard>
			<name>B250M PRO4 에즈윈</name>
			<company>ASRock</company>
			<price>100</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 B250</chipset>
		</motherboard>
		<motherboard>
			<name>AB350M PRO4 에즈윈</name>
			<company>ASRock</company>
			<price>103</price>
			<size>M-ATX</size>
			<socket>AM4</socket>
			<chipset>인텔 B350</chipset>
		</motherboard>
		<motherboard>
			<name>B250M 박격포</name>
			<company>MSI</company>
			<price>103</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 B250</chipset>
		</motherboard>
		<motherboard>
			<name>GA-B250M-DS3H 듀러블에디션 피씨디렉트</name>
			<company>GIGABYTE</company>
			<price>94</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 B250</chipset>
		</motherboard>
		<motherboard>
			<name>PRIME B250M-A STCOM</name>
			<company>ASUS</company>
			<price>101</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 B250</chipset>
		</motherboard>
		<motherboard>
			<name>B350M 박격포</name>
			<company>MSI</company>
			<price>108</price>
			<size>M-ATX</size>
			<socket>AM4</socket>
			<chipset>인텔 B350</chipset>
		</motherboard>
		<motherboard>
			<name>GA-H110M-DS2V 듀러블에디션 피씨디렉트</name>
			<company>GIGABYTE</company>
			<price>60</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 H110</chipset>
		</motherboard>
		<motherboard>
			<name>H110M-K iBORA</name>
			<company>ASUS</company>
			<price>60</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 H110</chipset>
		</motherboard>
		<motherboard>
			<name>H110M-HDV 에즈윈</name>
			<company>ASRock</company>
			<price>69</price>
			<size>Micro-ATX</size>
			<socket>LGA 1151</socket>
			<chipset>인텔 H110</chipset>
		</motherboard>
		<motherboard>
			<name>GA-AB350M-Gaming 3 게이밍에디션 제이씨현</name>
			<company>GIGABYTE</company>
			<price>106</price>
			<size>M-ATX</size>
			<socket>AM4</socket>
			<chipset>AMD B350</chipset>
		</motherboard>
	</MOTHERBOARDs>
	<PSUs>
		<psu>
			<name>Classic II</name>
			<company>마이크로닉스</company>
			<price>40</price>
			<size>ATX파워</size>
			<capacity>500</capacity>
		</psu>
		<psu>
			<name>HYPER K</name>
			<company>FSP</company>
			<price>41</price>
			<size>ATX파워</size>
			<capacity>500</capacity>
		</psu>
		<psu>
			<name>Classic II</name>
			<company>마이크로닉스</company>
			<price>49</price>
			<size>ATX파워</size>
			<capacity>600</capacity>
		</psu>
		<psu>
			<name>REX III </name>
			<company>POWEREX</company>
			<price>45</price>
			<size>ATX파워</size>
			<capacity>600</capacity>
		</psu>
		<psu>
			<name>ENERGY OPTIMUS Mach III</name>
			<company>EPITECH</company>
			<price>28</price>
			<size>ATX파워</size>
			<capacity>500</capacity>
		</psu>
		<psu>
			<name>SF-600R12A NOVA 80PLUS</name>
			<company>SuperFlower</company>
			<price>53</price>
			<size>ATX파워</size>
			<capacity>600</capacity>
		</psu>
		<psu>
			<name>Classic II</name>
			<company>마이크로닉스</company>
			<price>66</price>
			<size>ATX파워</size>
			<capacity>7600</capacity>
		</psu>
		<psu>
			<name>MasterWatt Lite 700 80PLUS Standard</name>
			<company>쿨러마스터</company>
			<price>65</price>
			<size>ATX파워</size>
			<capacity>700</capacity>
		</psu>
	</PSUs>
	<VGAs>
		<vga>
			<name>지포스 GTX1060 STORM X Dual D5</name>
			<company>이엠텍 XENON</company>
			<price>275</price>
			<capacity>3</capacity>
			<chipset>NVIDIA 지포스 GTX1060</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1060 STORM X Dual D5</name>
			<company>이엠텍 XENON</company>
			<price>358</price>
			<capacity>6</capacity>
			<chipset>NVIDIA 지포스 GTX1060</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1050 STORM X Nano D5</name>
			<company>이엠텍 XENON</company>
			<price>142</price>
			<capacity>2</capacity>
			<chipset>NVIDIA 지포스 GTX1050</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1050 Ti STORM X Dual OC D5</name>
			<company>이엠텍 XENON</company>
			<price>195</price>
			<capacity>4</capacity>
			<chipset>NVIDIA 지포스 GTX1050 Ti</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1080 Ti EXOC White D5X</name>
			<company>갤럭시</company>
			<price>915</price>
			<capacity>11</capacity>
			<chipset>NVIDIA 지포스 GTX1080 Ti</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1070 Super JETSTREAM D5</name>
			<company>이엠텍 XENON</company>
			<price>605</price>
			<capacity>8</capacity>
			<chipset>NVIDIA 지포스 GTX1070</chipset>
		</vga>
		<vga>
			<name>라데온 RX 560 OC D5</name>
			<company>SAPPHIRE</company>
			<price>130</price>
			<capacity>2</capacity>
			<chipset>AMD 라데온 RX 560</chipset>
		</vga>
		<vga>
			<name>지포스 GTX1050 OC D5 스톰</name>
			<company>MSI</company>
			<price>146</price>
			<capacity>2</capacity>
			<chipset>NVIDIA 지포스 GTX1050</chipset>
		</vga>
	</VGAs>
	<SSDs>
		<ssd>
			<name>850 EVO Series</name>
			<company>삼성전자</company>
			<price>105</price>
			<capacity>250</capacity>
			<readspeed>540</readspeed>
			<writespeed>520</writespeed>
		</ssd>
		<ssd>
			<name>Green SSD</name>
			<company>WD</company>
			<price>91</price>
			<capacity>240</capacity>
			<readspeed>540</readspeed>
			<writespeed>430</writespeed>
		</ssd>
		<ssd>
			<name>Crucial MX300 대원CTS</name>
			<company>마이크론</company>
			<price>107</price>
			<capacity>275</capacity>
			<readspeed>530</readspeed>
			<writespeed>500</writespeed>
		</ssd>
		<ssd>
			<name>960 EVO M.2 2280</name>
			<company>삼성전자</company>
			<price>149</price>
			<capacity>250</capacity>
			<readspeed>3200</readspeed>
			<writespeed>1500</writespeed>
		</ssd>
		<ssd>
			<name>Blue SSD</name>
			<company>WD</company>
			<price>103</price>
			<capacity>250</capacity>
			<readspeed>540</readspeed>
			<writespeed>500</writespeed>
